package:
  name: niapy
  version: "1.0.1"

build:
  number: 1
  noarch: generic

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/NiaOrg/NiaPy
  license: MIT
  summary: NiaPy - Python micro-framework for building nature-inspired algorithms.